# Generated by Django 2.2 on 2019-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191116_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('5', 5), ('4', 4), ('3', 3), ('2', 2), ('1', 1)], verbose_name='Rating'),
        ),
    ]
